from __future__ import annotations

import argparse
import json
from pathlib import Path
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen

DATAV_BASE_URL = "https://geo.datav.aliyun.com/areas_v3/bound"
GEOBOUNDARIES_API_URL = "https://www.geoboundaries.org/api/current/gbOpen/{iso}/{adm}/"
DEFAULT_OUTPUT = Path("visited_china_map/assets/china_city_boundaries.geojson")
DEFAULT_NEIGHBOR_OUTPUT = Path("visited_china_map/assets/neighbor_boundaries.geojson")
MUNICIPALITIES = {"110000", "120000", "310000", "500000", "810000", "820000", "710000"}
DEFAULT_NEIGHBOR_ISOS = (
    "AFG",
    "BTN",
    "IND",
    "KAZ",
    "KGZ",
    "LAO",
    "MNG",
    "MMR",
    "NPL",
    "PAK",
    "PRK",
    "RUS",
    "TJK",
    "VNM",
)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Download detailed offline China city boundary GeoJSON for the visited map service."
    )
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT))
    parser.add_argument("--base-url", default=DATAV_BASE_URL)
    parser.add_argument("--skip-china", action="store_true")
    parser.add_argument("--include-neighbors", action="store_true")
    parser.add_argument("--neighbor-output", default=str(DEFAULT_NEIGHBOR_OUTPUT))
    parser.add_argument("--neighbor-adm", default="ADM1", choices=("ADM0", "ADM1", "ADM2"))
    parser.add_argument("--neighbor-isos", default=",".join(DEFAULT_NEIGHBOR_ISOS))
    args = parser.parse_args()

    if not args.skip_china:
        output = Path(args.output)
        output.parent.mkdir(parents=True, exist_ok=True)
        feature_collection = build_city_feature_collection(args.base_url)
        output.write_text(json.dumps(feature_collection, ensure_ascii=False, separators=(",", ":")), encoding="utf-8")
        print(f"Wrote {len(feature_collection['features'])} features to {output}")

    if args.include_neighbors:
        neighbor_output = Path(args.neighbor_output)
        neighbor_output.parent.mkdir(parents=True, exist_ok=True)
        isos = [iso.strip().upper() for iso in args.neighbor_isos.split(",") if iso.strip()]
        neighbor_collection = build_neighbor_feature_collection(isos, args.neighbor_adm)
        neighbor_output.write_text(
            json.dumps(neighbor_collection, ensure_ascii=False, separators=(",", ":")),
            encoding="utf-8",
        )
        print(f"Wrote {len(neighbor_collection['features'])} neighbor features to {neighbor_output}")


def build_city_feature_collection(base_url: str) -> dict:
    china = fetch_geojson(f"{base_url}/100000_full.json")
    features = []

    for province in china["features"]:
        code = str(province.get("properties", {}).get("adcode", ""))
        if not code:
            continue

        if code in MUNICIPALITIES:
            features.append(simplify_feature(province))
            continue

        try:
            province_full = fetch_geojson(f"{base_url}/{code}_full.json")
        except (HTTPError, URLError) as error:
            print(f"Skipping {code}: {error}")
            continue

        for city in province_full.get("features", []):
            city_code = str(city.get("properties", {}).get("adcode", ""))
            if city_code:
                features.append(simplify_feature(city))

    return {
        "type": "FeatureCollection",
        "metadata": {
            "source": base_url,
            "note": "Generated by scripts/download_map_assets.py. Verify license and map review requirements before production release.",
        },
        "features": features,
    }


def fetch_geojson(url: str) -> dict:
    request = Request(
        url,
        headers={
            "User-Agent": "visited-china-map/0.1 (+offline asset builder)",
            "Accept": "application/json",
        },
    )
    with urlopen(request, timeout=30) as response:
        return json.loads(response.read().decode("utf-8"))


def build_neighbor_feature_collection(isos: list[str], adm: str) -> dict:
    features = []
    sources = []

    for iso in isos:
        try:
            metadata = fetch_geojson(GEOBOUNDARIES_API_URL.format(iso=iso, adm=adm))
            download_url = metadata.get("simplifiedGeometryGeoJSON") or metadata.get("gjDownloadURL")
            if not download_url:
                print(f"Skipping {iso}: geoBoundaries response has no GeoJSON download URL")
                continue

            geojson = fetch_geojson(download_url)
        except (HTTPError, URLError, TimeoutError, json.JSONDecodeError) as error:
            print(f"Skipping {iso}: {error}")
            continue

        source_name = metadata.get("boundaryName", iso)
        sources.append(
            {
                "iso": iso,
                "adm": adm,
                "name": source_name,
                "source": metadata.get("boundarySource", ""),
                "license": metadata.get("boundaryLicense", ""),
                "url": download_url,
            }
        )
        for feature in geojson.get("features", []):
            simplified = simplify_neighbor_feature(feature, iso, source_name)
            if simplified is not None:
                features.append(simplified)

    return {
        "type": "FeatureCollection",
        "metadata": {
            "source": "geoBoundaries",
            "api": GEOBOUNDARIES_API_URL,
            "adm": adm,
            "countries": isos,
            "sources": sources,
            "note": "Generated by scripts/download_map_assets.py. geoBoundaries datasets require attribution and license review before production release.",
        },
        "features": features,
    }


def simplify_feature(feature: dict) -> dict:
    properties = feature.get("properties", {})
    return {
        "type": "Feature",
        "properties": {
            "adcode": str(properties.get("adcode", "")),
            "name": properties.get("name") or properties.get("fullname") or "",
            "level": properties.get("level", "city"),
        },
        "geometry": feature.get("geometry"),
    }


def simplify_neighbor_feature(feature: dict, country_code: str, country_name: str) -> dict | None:
    properties = feature.get("properties", {})
    name = properties.get("shapeName") or properties.get("name") or properties.get("shapeISO")
    code = properties.get("shapeID") or properties.get("shapeISO") or f"{country_code}-{name}"
    geometry = feature.get("geometry")

    if not name or not geometry:
        return None

    return {
        "type": "Feature",
        "properties": {
            "code": str(code),
            "name": str(name),
            "country_code": country_code,
            "country_name": country_name,
            "shapeID": str(code),
            "shapeName": str(name),
            "shapeGroup": country_code,
        },
        "geometry": geometry,
    }


if __name__ == "__main__":
    main()
