from __future__ import annotations

import argparse
import json
from pathlib import Path
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen

DATAV_BASE_URL = "https://geo.datav.aliyun.com/areas_v3/bound"
DEFAULT_OUTPUT = Path("visited_china_map/assets/china_city_boundaries.geojson")
MUNICIPALITIES = {"110000", "120000", "310000", "500000", "810000", "820000", "710000"}


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Download detailed offline China city boundary GeoJSON for the visited map service."
    )
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT))
    parser.add_argument("--base-url", default=DATAV_BASE_URL)
    args = parser.parse_args()

    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    feature_collection = build_city_feature_collection(args.base_url)
    output.write_text(json.dumps(feature_collection, ensure_ascii=False, separators=(",", ":")), encoding="utf-8")
    print(f"Wrote {len(feature_collection['features'])} features to {output}")


def build_city_feature_collection(base_url: str) -> dict:
    china = fetch_geojson(f"{base_url}/100000_full.json")
    features = []

    for province in china["features"]:
        code = str(province.get("properties", {}).get("adcode", ""))
        if not code:
            continue

        if code in MUNICIPALITIES:
            features.append(simplify_feature(province))
            continue

        try:
            province_full = fetch_geojson(f"{base_url}/{code}_full.json")
        except (HTTPError, URLError) as error:
            print(f"Skipping {code}: {error}")
            continue

        for city in province_full.get("features", []):
            city_code = str(city.get("properties", {}).get("adcode", ""))
            if city_code:
                features.append(simplify_feature(city))

    return {
        "type": "FeatureCollection",
        "metadata": {
            "source": base_url,
            "note": "Generated by scripts/download_map_assets.py. Verify license and map review requirements before production release.",
        },
        "features": features,
    }


def fetch_geojson(url: str) -> dict:
    request = Request(
        url,
        headers={
            "User-Agent": "visited-china-map/0.1 (+offline asset builder)",
            "Accept": "application/json",
        },
    )
    with urlopen(request, timeout=30) as response:
        return json.loads(response.read().decode("utf-8"))


def simplify_feature(feature: dict) -> dict:
    properties = feature.get("properties", {})
    return {
        "type": "Feature",
        "properties": {
            "adcode": str(properties.get("adcode", "")),
            "name": properties.get("name") or properties.get("fullname") or "",
            "level": properties.get("level", "city"),
        },
        "geometry": feature.get("geometry"),
    }


if __name__ == "__main__":
    main()
